#!/usr/bin/env python
#
# SFRun is the same as Rerun but it'll almost never be updated and is contained
# in a single file rather than multiple files. Don't know or care about speed.
# This also does not go well with PEP8.
# License at end.
from __future__ import print_function
import sys
import os  # basics
import subprocess  # for processes.
import threading
try:
    import gi
    gi.require_version('Gtk', '3.0')  # inform the PC that we need GTK+ 3.
    from gi.repository import Gtk  # this is the GNOME depends
except ImportError as imper:
    print("Importing GObject failed!")
    print("Install GObject bindings.")
    print(imper)
    sys.exit(0)
builder = Gtk.Builder()
builder.add_from_string("""<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated with glade 3.20.0 -->
<interface>
  <requires lib="gtk+" version="3.20"/>
  <object class="GtkWindow" id="rerun">
    <property name="can_focus">False</property>
    <property name="resizable">False</property>
    <property name="window_position">center</property>
    <property name="default_width">250</property>
    <property name="default_height">85</property>
    <signal name="destroy" handler="on_window_destroy" swapped="no"/>
    <child>
      <object class="GtkBox" id="activatables">
        <property name="visible">True</property>
        <property name="can_focus">False</property>
        <property name="margin_top">4</property>
        <property name="margin_bottom">4</property>
        <property name="orientation">vertical</property>
        <child>
          <object class="GtkBox" id="primebox">
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <property name="margin_top">1</property>
            <child>
              <object class="GtkLabel" id="primelabel">
                <property name="visible">True</property>
                <property name="can_focus">False</property>
                <property name="margin_left">8</property>
                <property name="margin_right">8</property>
                <property name="margin_top">4</property>
                <property name="margin_bottom">4</property>
                <property name="label" translatable="yes">PRIME:</property>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">0</property>
              </packing>
            </child>
            <child>
              <object class="GtkBox" id="primeradios">
                <property name="visible">True</property>
                <property name="can_focus">False</property>
                <child>
                  <object class="GtkRadioButton" id="prdefault">
                    <property name="label" translatable="yes">Default</property>
                    <property name="visible">True</property>
                    <property name="can_focus">True</property>
                    <property name="receives_default">False</property>
                    <property name="active">True</property>
                    <property name="draw_indicator">True</property>
                  </object>
                  <packing>
                    <property name="expand">False</property>
                    <property name="fill">True</property>
                    <property name="position">0</property>
                  </packing>
                </child>
                <child>
                  <object class="GtkRadioButton" id="pron">
                    <property name="label" translatable="yes">Enabled</property>
                    <property name="visible">True</property>
                    <property name="can_focus">True</property>
                    <property name="receives_default">False</property>
                    <property name="active">True</property>
                    <property name="draw_indicator">True</property>
                    <property name="group">prdefault</property>
                  </object>
                  <packing>
                    <property name="expand">False</property>
                    <property name="fill">True</property>
                    <property name="position">1</property>
                  </packing>
                </child>
                <child>
                  <object class="GtkRadioButton" id="proff">
                    <property name="label" translatable="yes">Disabled</property>
                    <property name="visible">True</property>
                    <property name="can_focus">True</property>
                    <property name="receives_default">False</property>
                    <property name="active">True</property>
                    <property name="draw_indicator">True</property>
                    <property name="group">prdefault</property>
                  </object>
                  <packing>
                    <property name="expand">False</property>
                    <property name="fill">True</property>
                    <property name="position">2</property>
                  </packing>
                </child>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">1</property>
              </packing>
            </child>
            <child>
              <object class="GtkImage" id="primewhat">
                <property name="visible">True</property>
                <property name="can_focus">False</property>
                <property name="tooltip_markup" translatable="yes">&lt;b&gt;This is ONLY for switchable graphics devices&lt;/b&gt;
This has NO effect, negative or positive, on single graphics devices.
This sets the state of use of Discrete cards on switchable graphics devices. It is the same as using (or not using) the DRI_PRIME environment variable.</property>
                <property name="margin_left">8</property>
                <property name="margin_right">8</property>
                <property name="margin_top">4</property>
                <property name="margin_bottom">4</property>
                <property name="icon_name">help-info-symbolic</property>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="pack_type">end</property>
                <property name="position">2</property>
              </packing>
            </child>
          </object>
          <packing>
            <property name="expand">False</property>
            <property name="fill">True</property>
            <property name="position">0</property>
          </packing>
        </child>
        <child>
          <object class="GtkBox" id="rootbox">
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <property name="margin_top">1</property>
            <property name="spacing">8</property>
            <child>
              <object class="GtkLabel" id="rootlab">
                <property name="visible">True</property>
                <property name="can_focus">False</property>
                <property name="margin_left">8</property>
                <property name="margin_right">8</property>
                <property name="margin_top">4</property>
                <property name="margin_bottom">4</property>
                <property name="label" translatable="yes">Run As Root</property>
                <property name="use_markup">True</property>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">0</property>
              </packing>
            </child>
            <child>
              <object class="GtkEntry" id="rootpass">
                <property name="can_focus">True</property>
                <property name="tooltip_markup" translatable="yes">This is &lt;b&gt;NOT&lt;/b&gt; root password. Just the User password.</property>
                <property name="margin_top">2</property>
                <property name="margin_bottom">2</property>
                <property name="visibility">False</property>
                <property name="placeholder_text" translatable="yes">User Password</property>
              </object>
              <packing>
                <property name="expand">True</property>
                <property name="fill">True</property>
                <property name="position">1</property>
              </packing>
            </child>
            <child>
              <object class="GtkSwitch" id="rootrun">
                <property name="visible">True</property>
                <property name="can_focus">True</property>
                <property name="margin_left">8</property>
                <property name="margin_right">8</property>
                <property name="margin_top">4</property>
                <property name="margin_bottom">4</property>
                <accelerator key="r" signal="activate" modifiers="GDK_CONTROL_MASK"/>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="pack_type">end</property>
                <property name="position">2</property>
              </packing>
            </child>
            <child>
              <object class="GtkImage" id="rootsafe">
                <property name="visible">True</property>
                <property name="can_focus">False</property>
                <property name="tooltip_markup" translatable="yes">Running graphical applications as root is not recommended.
The recommended way to run anything as root is &lt;b&gt;pkexec&lt;/b&gt; and it works very well with X11.
However, in Rerun, &lt;b&gt;sudo&lt;/b&gt; is set to default as pkexec does not work with Wayland, which is the default display protocol for GNOME, which is what I use.</property>
                <property name="margin_top">4</property>
                <property name="margin_bottom">4</property>
                <property name="icon_name">help-info-symbolic</property>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">3</property>
              </packing>
            </child>
          </object>
          <packing>
            <property name="expand">False</property>
            <property name="fill">True</property>
            <property name="position">1</property>
          </packing>
        </child>
        <child>
          <object class="GtkBox" id="xfix">
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <property name="margin_bottom">4</property>
            <property name="spacing">8</property>
            <child>
              <object class="GtkButton" id="xfixbutton">
                <property name="label" translatable="yes">Fix 'cannot open display' on Root</property>
                <property name="visible">True</property>
                <property name="can_focus">True</property>
                <property name="receives_default">True</property>
                <property name="margin_left">8</property>
                <property name="margin_right">8</property>
                <property name="margin_top">4</property>
                <property name="margin_bottom">4</property>
                <property name="hexpand">True</property>
                <signal name="clicked" handler="xfixpress" swapped="no"/>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">0</property>
              </packing>
            </child>
            <child>
              <object class="GtkImage" id="xfixinfo">
                <property name="visible">True</property>
                <property name="can_focus">False</property>
                <property name="tooltip_markup" translatable="yes">&lt;b&gt;This is not usually needed&lt;/b&gt;
Sometimes, graphical applications may not run under root. This is usually due to xhost not allowing it to. So, this fix (or workaround) tells xhost to allow root to run graphical applications.</property>
                <property name="margin_left">8</property>
                <property name="margin_right">8</property>
                <property name="margin_top">4</property>
                <property name="margin_bottom">4</property>
                <property name="icon_name">help-info-symbolic</property>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">1</property>
              </packing>
            </child>
          </object>
          <packing>
            <property name="expand">False</property>
            <property name="fill">True</property>
            <property name="position">2</property>
          </packing>
        </child>
        <child>
          <object class="GtkBox" id="hovers">
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <property name="margin_left">6</property>
            <property name="margin_right">6</property>
            <property name="spacing">8</property>
            <child>
              <object class="GtkLabel" id="safety">
                <property name="visible">True</property>
                <property name="can_focus">False</property>
                <property name="tooltip_markup" translatable="yes">Rerun might be simple, as is the commandline. But just as in the commandline, you have to try and be safe.
 1. Do NOT randomly copy and paste commands from the internet.
 2. Review every command carefully may it be a root command or otherwise (eg: systemctl)
 3. Do not do random typing.
 4. Rerun uses the same syntax as shell. &lt;span size="x-small"&gt;[shell=True if you know python]&lt;/span&gt; This also means that you can run non-graphical commands like 'rm'. So, be careful and &lt;b&gt;DON'T&lt;/b&gt; run " rm * " or anything of the sort.</property>
                <property name="label" translatable="yes">&lt;b&gt;Safety Warnings and Tips&lt;/b&gt; &lt;span size="x-small"&gt;[hover over to read]&lt;/span&gt;</property>
                <property name="use_markup">True</property>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">0</property>
              </packing>
            </child>
            <child>
              <object class="GtkSeparator" id="hsep">
                <property name="visible">True</property>
                <property name="can_focus">False</property>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">1</property>
              </packing>
            </child>
            <child>
              <object class="GtkLabel" id="about">
                <property name="visible">True</property>
                <property name="can_focus">False</property>
                <property name="tooltip_markup" translatable="yes">&lt;span size="large"&gt;About Rerun&lt;/span&gt;
Rerun is a tool to run shell commands or applications directly while ignoring output and disallowing input. This allows quickly running applications like gedit or nautilus.
Rerun has a few tricks up its sleeve: Support for switchable graphics, Run As Root and a tiny fix.

Author: Mufeed Ali &lt;span size="x-small"&gt;[nightglare or mufeed20 or mufeed2000][mufeed.ali53@gmail.com]&lt;/span&gt;
License: GNU GPLv3</property>
                <property name="label" translatable="yes">&lt;b&gt;About Rerun&lt;/b&gt; &lt;span size="x-small"&gt;[hover to read]&lt;/span&gt;</property>
                <property name="use_markup">True</property>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">2</property>
              </packing>
            </child>
          </object>
          <packing>
            <property name="expand">False</property>
            <property name="fill">True</property>
            <property name="position">3</property>
          </packing>
        </child>
      </object>
    </child>
    <child type="titlebar">
      <object class="GtkHeaderBar" id="runhead">
        <property name="visible">True</property>
        <property name="can_focus">False</property>
        <property name="show_close_button">True</property>
        <property name="decoration_layout">minimize:close</property>
        <child type="title">
          <object class="GtkBox" id="mainbox">
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <property name="margin_left">8</property>
            <property name="margin_right">8</property>
            <property name="hexpand">True</property>
            <property name="spacing">8</property>
            <child>
              <object class="GtkEntry" id="command">
                <property name="visible">True</property>
                <property name="can_focus">True</property>
                <property name="has_focus">True</property>
                <property name="is_focus">True</property>
                <property name="can_default">True</property>
                <property name="has_default">True</property>
                <property name="hexpand">True</property>
                <signal name="activate" handler="on_run_entr" swapped="no"/>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">0</property>
              </packing>
            </child>
            <child>
              <object class="GtkSeparator" id="sep2">
                <property name="visible">True</property>
                <property name="can_focus">False</property>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">1</property>
              </packing>
            </child>
            <child>
              <object class="GtkButton" id="run">
                <property name="label" translatable="yes">Run</property>
                <property name="visible">True</property>
                <property name="can_focus">True</property>
                <property name="receives_default">True</property>
                <property name="relief">none</property>
                <signal name="clicked" handler="on_run_clicked" swapped="no"/>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">2</property>
              </packing>
            </child>
            <child>
              <object class="GtkSeparator" id="sep1">
                <property name="visible">True</property>
                <property name="can_focus">False</property>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">3</property>
              </packing>
            </child>
            <child>
              <object class="GtkLabel" id="maintitle">
                <property name="visible">True</property>
                <property name="can_focus">False</property>
                <property name="label" translatable="yes">Rerun
&lt;span size="x-small"&gt;Simple. Thats all.&lt;/span&gt;</property>
                <property name="use_markup">True</property>
                <property name="justify">right</property>
              </object>
              <packing>
                <property name="expand">False</property>
                <property name="fill">True</property>
                <property name="position">4</property>
              </packing>
            </child>
          </object>
        </child>
      </object>
    </child>
  </object>
</interface>
""")


def gload():
    window = builder.get_object('rerun')  # main window
    window.show_all()


gload()
NULLMAKER = open(os.devnull, 'w')
command = builder.get_object('command')
pron = builder.get_object('pron')
proff = builder.get_object('proff')
prdefault = builder.get_object('prdefault')
# This is needed for ignoring unwanted terminal output.


class thready(threading.Thread):
    def __init__(self, cmd, sin=None, root=False, rpass=None):
        threading.Thread.__init__(self)
        self.cmd = cmd
        self.root = root
        self.rpass = rpass
        self.sin = sin

    def run(self):
        p = subprocess.Popen(self.cmd, shell=True,
                             stdin=self.sin,
                             stdout=NULLMAKER,
                             stderr=subprocess.STDOUT,
                             universal_newlines=True)
        if self.root:
            p.stdin.write(self.rpass + '\n')
            p.stdin.close()


class rerunmain():
    def on_window_destroy(self, rerun):
        Gtk.main_quit()

    def regrun(self):
        if prdefault.get_active():
            thread = thready(command.get_text())
            thread.start()
            thread.join()
        elif pron.get_active():
            thread = thready("env DRI_PRIME=1 " + command.get_text())
            thread.start()
            thread.join()
        elif proff.get_active():
            thread = thready("env DRI_PRIME=0 " + command.get_text())
            thread.start()
            thread.join()

    def sudorun(self):
        rootpass = builder.get_object('rootpass')
        if prdefault.get_active():
            thread = thready('sudo -S "' + command.get_text().strip() +
                             '"', subprocess.PIPE, True, rootpass.get_text())
            thread.start()
            thread.join()
        elif pron.get_active():
            thread = thready("env DRI_PRIME=1 " + 'sudo -S "' +
                             command.get_text().strip() +
                             '"', subprocess.PIPE, True, rootpass.get_text())
            thread.start()
            thread.join()
        elif proff.get_active():
            thread = thready("env DRI_PRIME=0 " + 'sudo -S "' +
                             command.get_text().strip() +
                             '"', subprocess.PIPE, True, rootpass.get_text())
            thread.start()
            thread.join()

    def on_run_clicked(self, run):
        rootrun = builder.get_object('rootrun')
        try:
            if not command.get_text().strip() == '':
                if not rootrun.get_active():
                    self.regrun()
                else:
                    self.sudorun()
        except Exception as exe:
            print('Failed to run command!')
            print(exe)

    def on_run_entr(self, command):
        self.on_run_clicked('run')

    def xfixpress(self, xfixbutton):
        try:
            subprocess.Popen("xhost si:localuser:root", shell=True)
        except Exception as exe:
            print("Running the command failed. Something wrong with")
            print("your PC? This shouldn't be happening.")
            print(exe)


builder.connect_signals(rerunmain())
Gtk.main()

# LICENSING:
#
# SFRun
# Copyright (C) 2017 Mufeed Ali
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
#
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
